### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by ghost** [lukebaggett/dnscat2-powershell#2]
Hi mate, the script is amazing, and I was wondering if you have any plans of updating it to support the latest version of DNScat2 with all its new features?.

Cheers.

**Comment by lukebaggett** [comment]
Thanks! Although it's been a while, an update has arrived.

Full support for the command protocol has been added. Everything except encryption and non-TXT requests should work now, including tunnels. Let me know if you have any issues!

**Comment by lukebaggett** [comment]
All features have now been implemented.
