### ISSUE TITLE
Bug with russian text

### ISSUE THREAD

**Issue by donvitoz** [lukebaggett/dnscat2-powershell#3]
When I send any russian text - the dnscat2-powershell does not work properly.

**Comment by lukebaggett** [comment]
This appears to partly be an issue with the ruby dnscat2 server.

I started the ruby server and client written in C on the same system, like this:

Server: `ruby dnscat2.rb`
Client: `./dnscat --dns 'host=127.0.0.1,server=127.0.0.1' --console`

Then, I pasted Russian text into the client. It came through correctly and was printed on the server side. However, when pasting it into the server, you receive a `[[ ERROR ]] :: DNS: RCODE_NAME_ERROR` error from the client, or sequence number issues.

You might want to file this issue [here instead](https://github.com/iagox86/dnscat2/issues).
