### ISSUE TITLE
Some changes for money

### ISSUE THREAD

**Issue by donvitoz** [lukebaggett/dnscat2-powershell#4]
Hi!

Is it possible to make some changes for money?
I can pay you bitcoins for some changes in your powershell script dnscat2-powershell.
I found few bugs:
1) when you send any cyrillic symbol.
2) when you send kill command.

Please send me your email or jabber for more information.

Thanks!

**Comment by lukebaggett** [comment]
Number 2 should be fixed now. I'm not sure if I can fix number 1 since it appears to be a server problem.
