### ISSUE TITLE
Server goes down.

### ISSUE THREAD

**Issue by donvitoz** [lukebaggett/dnscat2-powershell#5]
I just running dnscat2 server and waiting for client.
I used --security=open.

ruby ./dnscat2.rb --security=open mydomain.com

dnscat2> /root/dnscat2/server/libs/dnser.rb:179:in `unpack': DNS packet was truncated (or we messed up parsing it)! (DNSer::Packet::FormatException)
        from /root/dnscat2/server/libs/dnser.rb:209:in `block in unpack_name'
        from /root/dnscat2/server/libs/dnser.rb:207:in `loop'
        from /root/dnscat2/server/libs/dnser.rb:207:in `unpack_name'
        from /root/dnscat2/server/libs/dnser.rb:484:in `parse'
        from /root/dnscat2/server/libs/dnser.rb:644:in `block in parse'
        from /root/dnscat2/server/libs/dnser.rb:643:in `upto'
        from /root/dnscat2/server/libs/dnser.rb:643:in `parse'
        from /root/dnscat2/server/libs/dnser.rb:847:in `block (2 levels) in on_request'
        from /root/dnscat2/server/libs/dnser.rb:843:in `loop'
        from /root/dnscat2/server/libs/dnser.rb:843:in `block in on_request'

After this error dnscat2-server goes down and I should re-run it.
I did not sent a client.

Thanks.

**Comment by lukebaggett** [comment]
At the moment dnscat2-powershell hasn't been updated to support the new dnscat2 server. An update is in the works which should solve this issue.

**Comment by lukebaggett** [comment]
The script has been updated to support the new server. Let me know if you're still having this issue.
